services:
  - type: web
    name: otp-bot
    runtime: python
    buildCommand: |
      apt-get update && \
      apt-get install -y wget unzip curl && \
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
      apt-get install -y ./google-chrome-stable_current_amd64.deb
      pip install -r requirements.txt
    startCommand: python otp_bot.py
    envVars:
      - key: PORT
        value: 10000
