services:
  - type: web
    name: otp-bot
    runtime: python
    buildCommand: |
      apt-get update && \
      apt-get install -y chromium && \
      pip install -r requirements.txt
    startCommand: python otp_bot.py
    envVars:
      - key: PORT
        value: 10000
