services:
  - type: web
    name: otp-bot
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y chromium
      apt-get install -y \
          fonts-liberation \
          libappindicator3-1 \
          libasound2 \
          libatk-bridge2.0-0 \
          libatk1.0-0 \
          libcups2 \
          libdbus-glib-1-2 \
          libgdk-pixbuf2.0-0 \
          libnspr4 \
          libnss3 \
          libx11-xcb1 \
          libxcomposite1 \
          libxrandr2 \
          libxss1 \
          libxtst6 \
          xdg-utils
    startCommand: python otp_bot.py
    envVars:
      TELEGRAM_BOT_TOKEN: "7681288998:AAE9OzduHanSU3drsnAsCmOY2na7af0OVro"
      TELEGRAM_CHAT_ID: "1002541578739"
      TELEGRAM_USER_ID: "6864709585"
      EMAIL: "Unseendevx2@gmail.com"
      PASSWORD: "RheaxDev@2025"
