services:
  - type: worker
    name: otp-telegram-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python otp_bot.py
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7681288998:AAE9OzduHanSU3drsnAsCmOY2na7af0OVro
      - key: TELEGRAM_CHAT_ID
        value: 1002541578739
